const DATE_FORMAT = 'D MMM';
const DATE_FORMAT_MAX = 'YYYY-MM-DD';
const TIME_FORMAT = 'HH:mm';
const DATA_TIME_FORMAT = 'YYYY-MM-DDTHH:mm';

export { DATE_FORMAT, DATE_FORMAT_MAX, TIME_FORMAT, DATA_TIME_FORMAT };
